/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        night: {
          950: 'var(--night-950)',
          900: 'var(--night-900)',
          800: 'var(--night-800)',
          700: 'var(--night-700)',
          600: 'var(--night-600)',
        },
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        paper: 'var(--paper)',
        'paper-edge': 'var(--paper-edge)',
        ink: 'var(--ink)',
        'ink-soft': 'var(--ink-soft)',
        'ink-muted': 'var(--ink-muted)',
        text: 'var(--text)',
        'text-muted': 'var(--text-muted)',
        'text-faint': 'var(--text-faint)',
        gold: 'var(--gold)',
        'gold-bright': 'var(--gold-bright)',
        'gold-deep': 'var(--gold-deep)',
        teal: 'var(--teal)',
        rust: 'var(--rust)',
        moss: 'var(--moss)',
        line: 'var(--line)',
        'line-2': 'var(--line-2)',
        tier: {
          bronze: 'var(--tier-bronze)',
          silver: 'var(--tier-silver)',
          gold: 'var(--tier-gold)',
          platinum: 'var(--tier-platinum)',
        },
      },
      fontFamily: {
        serif: ['"Literata Variable"', 'Georgia', 'serif'],
        display: ['"Fraunces Variable"', 'Georgia', 'serif'],
        sans: ['"Figtree Variable"', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      fontSize: {
        display: ['clamp(2rem, 1.5rem + 2vw, 3.2rem)', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
        h1: ['clamp(1.75rem, 1.35rem + 1.4vw, 2.5rem)', { lineHeight: '1.1', letterSpacing: '-0.015em' }],
        h2: ['clamp(1.3rem, 1.12rem + 0.7vw, 1.65rem)', { lineHeight: '1.2' }],
        h3: ['1.15rem', { lineHeight: '1.35' }],
        body: ['1rem', { lineHeight: '1.6' }],
        caption: ['0.875rem', { lineHeight: '1.45' }],
        micro: ['0.75rem', { lineHeight: '1.35', letterSpacing: '0.02em' }],
        write: ['1.1875rem', { lineHeight: '2rem' }],
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        paper: 'var(--shadow-paper)',
        lift: 'var(--shadow-lift)',
        'gold-glow': '0 10px 24px -8px rgba(222, 159, 44, 0.6)',
      },
      animation: {
        'fade-in': 'fade-in 0.4s ease-out both',
        'slide-up': 'slide-up 0.55s cubic-bezier(0.2, 0.8, 0.2, 1) both',
        'pulse-soft': 'pulse-soft 2.4s ease-in-out infinite',
        shake: 'shake 0.45s cubic-bezier(.36,.07,.19,.97) both',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(14px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'pulse-soft': {
          '0%,100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
        shake: {
          '10%,90%': { transform: 'translateX(-2px)' },
          '20%,80%': { transform: 'translateX(4px)' },
          '30%,50%,70%': { transform: 'translateX(-8px)' },
          '40%,60%': { transform: 'translateX(8px)' },
        },
      },
    },
  },
  plugins: [],
};
